"""empty message

Revision ID: 429a8fff96b6
Revises: 9546f373afd1
Create Date: 2021-06-08 23:13:11.534842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "429a8fff96b6"
down_revision = "9546f373afd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_ratings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quote_ratings_quote_id"), "quote_ratings", ["quote_id"], unique=False
    )
    op.create_index(
        op.f("ix_quote_ratings_timestamp"), "quote_ratings", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_quote_ratings_user_id"), "quote_ratings", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quote_ratings_user_id"), table_name="quote_ratings")
    op.drop_index(op.f("ix_quote_ratings_timestamp"), table_name="quote_ratings")
    op.drop_index(op.f("ix_quote_ratings_quote_id"), table_name="quote_ratings")
    op.drop_table("quote_ratings")
    # ### end Alembic commands ###
