"""
Create 2 tables (users and attendances)

Revision ID: 9546f373afd1
Revises:
Create Date: 2020-10-09 09:21:01.507408

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9546f373afd1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendances_timestamp"), "attendances", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendances_timestamp"), table_name="attendances")
    op.drop_table("attendances")
    op.drop_table("users")
    # ### end Alembic commands ###
