"""add rating table

Revision ID: 968fabf1872c
Revises: 9546f373afd1
Create Date: 2021-06-08 22:02:01.835048

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "968fabf1872c"
down_revision = "9546f373afd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_ratings",
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("quote_id"),
    )
    op.create_index(
        op.f("ix_quote_ratings_timestamp"), "quote_ratings", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quote_ratings_timestamp"), table_name="quote_ratings")
    op.drop_table("quote_ratings")
    # ### end Alembic commands ###
